"use client";

import { useEffect, useMemo, useState } from "react";
import Image from "next/image";
import { RankBadge, RankIcon } from "@/components/RankBadge";

interface MatchRow {
  id:string; date:string; map:string; mode:string; result:"win"|"loss"|"tie"|"unknown"; score:string; banned:boolean;
  kills:number; deaths:number; assists:number; headshots:number; hsPercent:number; kd:number; adr:number; damage:number; rounds:number;
  rating:number; ctRating:number; tRating:number; scorePoints:number; mvps:number; accuracy:number; preaim:number; reaction:number; sprayAccuracy:number; survived:number;
  multi1k:number; multi2k:number; multi3k:number; multi4k:number; multi5k:number; tradeKills:number; tradeKillSuccess:number; tradedDeaths:number; tradedDeathSuccess:number;
  flashAssists:number; flashThrown:number; heThrown:number; molotovThrown:number; smokeThrown:number; roundsWon:number; roundsLost:number; shotsFired:number; shotsHit:number;
  enemyShots:number; headshotHits:number; flashKills:number; counterStrafe:number; utilityDeath:number; tradeAttempts:number; tradeOpps:number; tradedDeathAttempts:number; tradedDeathOpps:number;
}
interface Analytics { matches:MatchRow[]; sampleSize:number; totalTrackedMatches:number; firstMatchDate:string|null; totals:Record<string,number>; ratings:Record<string,number|null>; lifetimeStats:Record<string,number|null>; ranks:Record<string,any>; mapStats:{map:string;matches:number;wins:number;kills:number;deaths:number;damage:number;rounds:number;winRate:number;kd:number;adr:number;rating:number}[]; source:string; }
interface LookupResult {
  steamid64:string; profile:{steamid:string;personaname:string;profileurl:string;avatarfull:string;personastate:number;communityvisibilitystate:number;timecreated?:number;loccountrycode?:string};
  bans:{VACBanned:boolean;NumberOfVACBans:number;NumberOfGameBans:number;DaysSinceLastBan:number;CommunityBanned:boolean}|null; steamLevel:number|null;
  playtime:{forever_minutes:number;recent_minutes:number;visible:boolean};
  premier:{rating:number;previousRating:number|null;ratingChange:number|null;season:number|null;recentGames:{gameId:string;mapName:string;matchResult:string;skillLevel:number;rankType:number|null;elo:number|null}[];source:string;sourceUrl:string;fetchedAt:string}|null;
  leetify:Analytics|null; faceit:null|{nickname:string;avatar:string;country:string;url?:string;cs2:{skill_level:number;faceit_elo:number;region:string}|null;stats:any|null};
}
const examples=["76561197971307841","https://steamcommunity.com/id/donk"];
const RANK_NAMES=["Silver I","Silver II","Silver III","Silver IV","Silver Elite","Silver Elite Master","Gold Nova I","Gold Nova II","Gold Nova III","Gold Nova Master","Master Guardian I","Master Guardian II","Master Guardian Elite","Distinguished Master Guardian","Legendary Eagle","Legendary Eagle Master","Supreme Master First Class","The Global Elite"];
function n(v:unknown,digits=0){return typeof v==="number"&&Number.isFinite(v)?v.toLocaleString("ru-RU",{maximumFractionDigits:digits}):"—"}
function pct(v:unknown,digits=1){return typeof v==="number"&&Number.isFinite(v)?`${v.toFixed(digits)}%`:"—"}
function date(v?:string|number|null){if(!v)return"—";const d=typeof v==="number"?new Date(v*1000):new Date(v);return Number.isNaN(d.getTime())?"—":d.toLocaleDateString("ru-RU",{day:"2-digit",month:"short",year:"numeric"})}
function hours(min:number){return Math.round(min/60).toLocaleString("ru-RU")}
function StatCard({label,value,sub}:{label:string;value:string;sub?:string}){return <div className="stat-card"><div className="label">{label}</div><div className="value">{value}</div>{sub&&<div className="sub">{sub}</div>}</div>}
function Section({title,kicker,children}:{title:string;kicker:string;children:React.ReactNode}){return <section className="section"><div className="section-head"><div><div className="kicker">{kicker}</div><h2>{title}</h2></div></div>{children}</section>}
function BarStat({label,value,max=100,suffix=""}:{label:string;value:number;max?:number;suffix?:string}){const width=Math.max(0,Math.min(100,(value/max)*100));return <div className="bar-row"><div className="bar-top"><span>{label}</span><b>{value.toFixed(1)}{suffix}</b></div><div className="bar"><span style={{width:`${width}%`}}/></div></div>}
function competitiveRanks(raw:any[]|undefined){return (raw??[]).map((r:any)=>({map:String(r.map_name??r.mapName??r.map??"Competitive"),level:Number(r.rank_id??r.rankId??r.rank??r.skill_level??r.level)})).filter(r=>Number.isFinite(r.level)&&r.level>0)}
function premierTier(r:number|null){if(r===null)return{label:"Unrated",color:"#7d8790",range:"—"};if(r<5000)return{label:"Grey",color:"#a0a8ad",range:"0–4,999"};if(r<10000)return{label:"Light Blue",color:"#74c8ff",range:"5,000–9,999"};if(r<15000)return{label:"Blue",color:"#4f8cff",range:"10,000–14,999"};if(r<20000)return{label:"Purple",color:"#a970ff",range:"15,000–19,999"};if(r<25000)return{label:"Pink",color:"#e879f9",range:"20,000–24,999"};if(r<30000)return{label:"Red",color:"#fb5d67",range:"25,000–29,999"};return{label:"Gold",color:"#f5c451",range:"30,000+"}}

export default function Home(){
  const [query,setQuery]=useState(""); const [result,setResult]=useState<LookupResult|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState<string|null>(null);
  const [tab,setTab]=useState<"overview"|"matches"|"performance">("overview"); const [theme,setTheme]=useState<"dark"|"light">("dark");
  useEffect(()=>{const saved=localStorage.getItem("radar-theme") as "dark"|"light"|null;const next=saved??"dark";setTheme(next);document.documentElement.dataset.theme=next},[]);
  function toggleTheme(){const next=theme==="dark"?"light":"dark";setTheme(next);document.documentElement.dataset.theme=next;localStorage.setItem("radar-theme",next)}
  async function search(e?:React.FormEvent){e?.preventDefault();if(!query.trim())return;setLoading(true);setError(null);try{const res=await fetch(`/api/lookup?q=${encodeURIComponent(query.trim())}`);const data=await res.json();if(!res.ok)throw new Error(data.error??"Ошибка запроса");setResult(data);setTab("overview")}catch(e){setError(e instanceof Error?e.message:"Не удалось загрузить статистику")}finally{setLoading(false)}}
  const a=result?.leetify,t=a?.totals,recent=a?.matches??[]; const latestRating=result?.premier?.rating??(typeof a?.ranks?.premier==="number"?a.ranks.premier:null); const tier=premierTier(latestRating); const competitive=competitiveRanks(a?.ranks?.competitive);
  const performance=useMemo(()=>{if(!recent.length)return null;const sorted=[...recent].sort((x,y)=>y.rating-x.rating);return{best:sorted[0],worst:sorted[sorted.length-1]}},[recent]);
  const totalShots=t?.shotsFired??0, hitRate=totalShots?(t?.shotsHit??0)/totalShots*100:0;

  return <main>
    <header className="topbar"><div className="brand"><span className="brand-mark">R</span><div><strong>RADAR</strong><small>CS2 PLAYER INTELLIGENCE</small></div></div><div className="top-actions"><div className="live"><i/> LIVE DATA</div><button className="theme-toggle" onClick={toggleTheme} aria-label="Сменить тему"><span>{theme==="dark"?"☼":"☾"}</span>{theme==="dark"?"LIGHT":"DARK"}</button></div></header>
    <div className="hero"><div className="hero-grid"/><div className="hero-inner"><div className="eyebrow">PLAYER DATABASE / CS2</div><h1>Статистика<br/><span>без лишнего</span></h1><p>Premier rating, реальные иконки рангов, 30 последних матчей, performance, utility и расширенные показатели игрока.</p><form onSubmit={search} className="search"><div className="search-icon">⌕</div><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="SteamID64, Steam URL или vanity URL"/><button disabled={loading}>{loading?"ЗАГРУЗКА":"ANALYZE"}</button></form><div className="examples">Быстрый поиск: {examples.map(x=><button key={x} type="button" onClick={()=>setQuery(x)}>{x}</button>)}</div></div></div>
    <div className="container">
      {error&&<div className="error">{error}</div>}
      {!result&&!loading&&<div className="empty"><div className="empty-number">01</div><h2>Введите Steam-профиль</h2><p>Получите профиль Steam, Premier, классические ранги, историю матчей и расширенную статистику.</p></div>}
      {result&&<>
        <section className="profile-head"><Image src={result.profile.avatarfull} alt="" width={78} height={78} className="avatar"/><div className="identity"><div className="identity-line"><h2>{result.profile.personaname}</h2>{result.profile.personastate===1&&<span className="online">ONLINE</span>}</div><div className="steamid">{result.steamid64}</div><div className="badges">{result.bans?.VACBanned?<span className="badge danger">VAC ×{result.bans.NumberOfVACBans}</span>:<span className="badge good">CLEAN</span>}{result.profile.loccountrycode&&<span className="badge">{result.profile.loccountrycode}</span>}{result.steamLevel!==null&&<span className="badge">STEAM LVL {result.steamLevel}</span>}</div></div><div className="profile-rank-mini"><span>PREMIER</span><b style={{color:tier.color}}>{n(latestRating)}</b><small>{tier.label}</small></div><a className="profile-link" href={result.profile.profileurl} target="_blank" rel="noreferrer">STEAM ↗</a></section>
        <nav className="tabs">{([['overview','Обзор'],['matches','30 матчей'],['performance','Performance']] as const).map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</nav>
        {tab==="overview"&&<div className="stack">
          <Section kicker="PREMIER" title="Рейтинг сезона"><div className="rating-layout"><div className="rating-main"><div className="rating-icon-row"><div className="premier-orb" style={{borderColor:tier.color,boxShadow:`0 0 0 1px ${tier.color}22, inset 0 0 40px ${tier.color}14`}}><span style={{color:tier.color}}>{latestRating!==null?n(latestRating):"—"}</span></div><div><span>CURRENT RATING</span><strong style={{color:tier.color}}>{latestRating!==null?n(latestRating):"—"}</strong><div className="tier-name">{tier.label} <em>{tier.range}</em></div></div></div><div className="rating-meta">{result.premier?.ratingChange!==null&&result.premier?.ratingChange!==undefined?<b className={result.premier.ratingChange>=0?'positive':'negative'}>{result.premier.ratingChange>=0?'+':''}{n(result.premier.ratingChange)} после последней игры</b>:"Рейтинг из доступного источника"}</div></div><div className="rating-side"><div><span>SEASON</span><b>{result.premier?.season?`S${result.premier.season}`:"—"}</b></div><div><span>TRACKED</span><b>{n(a?.totalTrackedMatches)}</b></div><div><span>30-MATCH WR</span><b>{pct(t?.winRate)}</b></div><div><span>AVG RATING</span><b>{n(t?.rating,2)}</b></div></div></div></Section>
          <Section kicker="RANKS" title="Иконки рангов"><div className="rank-grid">{competitive.length?competitive.map((r,i)=><div className="rank-card" key={`${r.map}-${i}`}><RankBadge level={r.level} size={94}/><div className="rank-map">{r.map}</div><small>{RANK_NAMES[Math.round(r.level)-1]??`Rank ${r.level}`}</small></div>):<div className="rank-empty">Leetify не вернул классические competitive ranks для этого профиля.</div>}<div className="rank-card premier-card"><div className="premier-tier-icon" style={{borderColor:tier.color,background:`linear-gradient(135deg,${tier.color}20,transparent)`}}><span style={{color:tier.color}}>CS</span></div><div className="rank-map">Premier</div><small style={{color:tier.color}}>{tier.label} · {tier.range}</small></div></div></Section>
          <Section kicker="LAST 30" title="Основные показатели"><div className="stats-grid"><StatCard label="K/D" value={n(t?.kd,2)} sub={`${n(t?.kills)} K / ${n(t?.deaths)} D`}/><StatCard label="ADR" value={n(t?.adr,1)} sub={`${n(t?.damage)} damage`}/><StatCard label="HS%" value={pct(t?.hsPercent)} sub={`${n(t?.headshots)} headshots`}/><StatCard label="WIN RATE" value={pct(t?.winRate)} sub={`${n(t?.wins)}W / ${n(t?.losses)}L`}/><StatCard label="RATING" value={n(t?.rating,2)} sub="Leetify"/><StatCard label="ROUNDS" value={n(t?.rounds)} sub={`${n(t?.roundsWon)} won / ${n(t?.roundsLost)} lost`}/></div></Section>
          <div className="two-col"><Section kicker="LEETIFY" title="Performance"><div className="bars"><BarStat label="Aim" value={Number(a?.ratings.aim??0)}/><BarStat label="Positioning" value={Number(a?.ratings.positioning??0)}/><BarStat label="Utility" value={Number(a?.ratings.utility??0)}/><BarStat label="Clutch" value={Number(a?.ratings.clutch??0)}/><BarStat label="Opening" value={Number(a?.ratings.opening??0)}/></div></Section><Section kicker="MATCH QUALITY" title="Лучшие / худшие">{performance?<div className="best-list"><div><span>BEST GAME</span><b>{performance.best.map}</b><strong>{n(performance.best.rating,2)}</strong><small>{performance.best.score} · {performance.best.kills}/{performance.best.deaths}/{performance.best.assists}</small></div><div><span>LOWEST</span><b>{performance.worst.map}</b><strong>{n(performance.worst.rating,2)}</strong><small>{performance.worst.score} · {performance.worst.kills}/{performance.worst.deaths}/{performance.worst.assists}</small></div></div>:<div className="muted">Нет обработанных матчей.</div>}</Section></div>
          <Section kicker="AIM / MECHANICS" title="Стрельба"><div className="stats-grid six"><StatCard label="ACCURACY" value={pct(t?.accuracy)}/><StatCard label="SHOT HIT" value={pct(hitRate)} sub={`${n(t?.shotsHit)} / ${n(t?.shotsFired)}`}/><StatCard label="HEADSHOT" value={pct(t?.headshotHits&&t?.shotsHit?(t.headshotHits/t.shotsHit*100):0)}/><StatCard label="PREAIM" value={n(t?.preaim,2)}/><StatCard label="REACTION" value={`${n(t?.reaction,0)} ms`}/><StatCard label="SPRAY" value={pct(t?.sprayAccuracy)}/></div></Section>
          <Section kicker="UTILITY / TEAMPLAY" title="Расширенные показатели"><div className="stats-grid six"><StatCard label="MVPS" value={n(t?.mvps)}/><StatCard label="1K / 2K" value={`${n(t?.multi1k)} / ${n(t?.multi2k)}`}/><StatCard label="3K / 4K / 5K" value={`${n(t?.multi3k)} / ${n(t?.multi4k)} / ${n(t?.multi5k)}`}/><StatCard label="FLASH ASSISTS" value={n(t?.flashAssists)}/><StatCard label="FLASH KILLS" value={n(t?.flashKills)}/><StatCard label="HE / MOLLY / SMOKE" value={`${n(t?.heThrown)} / ${n(t?.molotovThrown)} / ${n(t?.smokeThrown)}`}/><StatCard label="TRADE KILLS" value={n(t?.tradeKills)} sub={pct(t?.tradeKillSuccess)}/><StatCard label="TRADED DEATHS" value={n(t?.tradedDeaths)} sub={pct(t?.tradedDeathSuccess)}/><StatCard label="COUNTER-STRAFE" value={pct(t?.counterStrafe)}/><StatCard label="SURVIVED" value={pct(t?.survived)}/><StatCard label="UTILITY ON DEATH" value={n(a?.totals?.utilityDeath,2)}/><StatCard label="FACEIT ELO" value={n(result.faceit?.cs2?.faceit_elo)}/></div></Section>
          <Section kicker="MAPS" title="Статистика по картам"><div className="match-table-wrap"><table><thead><tr><th>MAP</th><th>GAMES</th><th>WINRATE</th><th>K/D</th><th>ADR</th><th>RATING</th></tr></thead><tbody>{(a?.mapStats??[]).map(m=><tr key={m.map}><td><b>{m.map.replace(/^de_/,'')}</b></td><td>{m.matches}</td><td>{pct(m.winRate)}</td><td>{n(m.kd,2)}</td><td>{n(m.adr,1)}</td><td><strong>{n(m.rating,2)}</strong></td></tr>)}</tbody></table></div></Section>
          <Section kicker="STEAM" title="Аккаунт"><div className="stats-grid"><StatCard label="CS2 PLAYTIME" value={result.playtime.visible?`${hours(result.playtime.forever_minutes)} ч`:"скрыто"}/><StatCard label="2 WEEKS" value={result.playtime.visible?`${hours(result.playtime.recent_minutes)} ч`:"скрыто"}/><StatCard label="ACCOUNT CREATED" value={date(result.profile.timecreated)}/><StatCard label="FIRST TRACKED" value={date(a?.firstMatchDate)}/><StatCard label="FACEIT LEVEL" value={n(result.faceit?.cs2?.skill_level)}/><StatCard label="FACEIT ELO" value={n(result.faceit?.cs2?.faceit_elo)}/></div></Section>
        </div>}
        {tab==="matches"&&<Section kicker="MATCH HISTORY" title="Последние 30 игр"><div className="match-table-wrap"><table><thead><tr><th>DATE</th><th>MAP</th><th>RESULT</th><th>SCORE</th><th>K/D/A</th><th>ADR</th><th>HS%</th><th>RATING</th></tr></thead><tbody>{recent.map(m=><tr key={m.id}><td>{date(m.date)}</td><td><b>{m.map.replace(/^de_/,'')}</b><small>{m.mode}</small></td><td><span className={`result ${m.result}`}>{m.result==='win'?'WIN':m.result==='loss'?'LOSS':m.result==='tie'?'TIE':'—'}</span></td><td>{m.score}</td><td>{m.kills}/{m.deaths}/{m.assists}</td><td>{n(m.adr,1)}</td><td>{pct(m.hsPercent)}</td><td><strong>{n(m.rating,2)}</strong></td></tr>)}</tbody></table></div></Section>}
        {tab==="performance"&&<div className="stack"><Section kicker="30 MATCH SAMPLE" title="Вся доступная статистика"><div className="stats-grid six">{Object.entries(t??{}).map(([key,value])=><StatCard key={key} label={key.replaceAll("_"," ")} value={typeof value==='number'?n(value,2):'—'}/>)}</div></Section><Section kicker="LIFETIME / LEETIFY" title="Lifetime metrics"><div className="stats-grid six">{Object.entries(a?.lifetimeStats??{}).map(([key,value])=><StatCard key={key} label={key.replaceAll("_"," ")} value={typeof value==='number'?n(value,2):'—'}/>)}</div></Section></div>}
        <footer className="footer">Data provided by Leetify · Rank icons: CSStats static assets · Premier данные могут измениться вместе с внешними источниками. <a href="https://leetify.com/" target="_blank" rel="noreferrer">Leetify ↗</a> · <a href="https://csstats.gg/" target="_blank" rel="noreferrer">CSStats ↗</a></footer>
      </>}
    </div>
  </main>
}
