"use client";
import {useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';

export default function Home(){const router=useRouter();const [q,setQ]=useState(''),[theme,setTheme]=useState<'dark'|'light'>('dark'),[busy,setBusy]=useState(false);
 useEffect(()=>{const t=(localStorage.getItem('radar-theme') as 'dark'|'light')||'dark';setTheme(t);document.documentElement.dataset.theme=t;},[]);
 const toggle=()=>{const t=theme==='dark'?'light':'dark';setTheme(t);document.documentElement.dataset.theme=t;localStorage.setItem('radar-theme',t)};
 async function go(e:any){e.preventDefault();if(!q.trim())return;setBusy(true);try{const res=await fetch('/api/lookup?q='+encodeURIComponent(q.trim()),{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Player not found');router.push('/player/'+data.steamid64);}catch(e){alert(e instanceof Error?e.message:'Ошибка');}finally{setBusy(false)}}
 return <div className="landing"><header className="topbar"><button className="brand" onClick={()=>router.push('/')}><span>R</span><b>RADAR<small>CS2 PLAYER DATA</small></b></button><button className="theme" onClick={toggle}>{theme==='dark'?'LIGHT':'DARK'}</button></header><main className="landing-main"><span className="kicker">CS2 / PLAYER ANALYTICS</span><h1>Player data,<br/><i>properly presented.</i></h1><p>Premier, real competitive ranks, FACEIT, match history and performance — each player gets a permanent profile at <b>/player/steamid64</b>.</p><form onSubmit={go}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="SteamID64 / Steam profile URL / vanity URL"/><button disabled={busy}>{busy?'LOADING':'OPEN PROFILE'}</button></form><div className="landing-notes"><span>01 / STEAM</span><span>02 / PREMIER</span><span>03 / FACEIT</span><span>04 / MATCHES</span></div></main></div>}
