"use client";
import {useEffect,useMemo,useState} from 'react';
import type {ReactNode} from 'react';
import {useRouter} from 'next/navigation';
import {RankBadge} from '@/components/RankBadge';

const N=(v:any,d=0)=>typeof v==='number'&&Number.isFinite(v)?v.toLocaleString('ru-RU',{maximumFractionDigits:d}):'—';
const P=(v:any)=>typeof v==='number'&&Number.isFinite(v)?v.toFixed(1)+'%':'—';
const D=(v:any)=>{if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleDateString('ru-RU',{day:'2-digit',month:'short',year:'numeric'});};
const tier=(r:any)=>typeof r!=='number'?['UNRATED','#87909b']:r<5000?['GREY','#aeb6c0']:r<10000?['LIGHT BLUE','#66c7ff']:r<15000?['BLUE','#5b8cff']:r<20000?['PURPLE','#a876ff']:r<25000?['PINK','#ed6ee7']:r<30000?['RED','#ff5f68']:['GOLD','#f0c55b'];
const labels:Record<string,string>={kd:'K/D',hltvRating:'HLTV rating',winRate:'Win rate',played:'Matches',wins:'Wins',losses:'Losses',ties:'Ties',hsPercent:'HS %',kills:'Kills',deaths:'Deaths',assists:'Assists',headshots:'Headshots',adr:'ADR',damage:'Damage',rounds:'Rounds',accuracy:'Accuracy',preaim:'Preaim',reaction:'Reaction time',sprayAccuracy:'Spray accuracy',survived:'Rounds survived',counterStrafe:'Counter-strafe',tradeKillSuccess:'Trade kill success',tradedDeathSuccess:'Traded death success',roundsWon:'Rounds won',roundsLost:'Rounds lost',shotsFired:'Shots fired',shotsHit:'Shots hit',headshotHits:'Headshot hits',flashKills:'Flash kills',flashAssists:'Flash assists',flashThrown:'Flash thrown',heThrown:'HE thrown',molotovThrown:'Molotovs',smokeThrown:'Smokes',mvps:'MVPs',multi1k:'1K',multi2k:'2K',multi3k:'3K',multi4k:'4K',multi5k:'5K',tradeKills:'Trade kills',tradedDeaths:'Traded deaths'};
function Metric({label,value,sub}:{label:string,value:any,sub?:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}
function Section({eyebrow,title,children}:{eyebrow:string,title:string,children:ReactNode}){return <section className="section"><div className="section-head"><span>{eyebrow}</span><h2>{title}</h2></div>{children}</section>}
function Matches({rows}:{rows:any[]}){return <div className="match-list">{rows.length?rows.map((m,i)=><article className="match-row" key={m.id||i}><div className="match-map"><span className="map-dot"/><div><b>{String(m.map||'—').replace(/^de_/,'')}</b><small>{D(m.date)}</small></div></div><div className={`result ${m.result||''}`}>{m.result==='win'?'WIN':m.result==='loss'?'LOSS':m.result==='tie'?'DRAW':'MATCH'}</div><div className="score"><b>{m.score||'—'}</b><small>K/D/A {N(m.kills)}/{N(m.deaths)}/{N(m.assists)}</small></div><div className="match-stat"><span>ADR</span><b>{N(m.adr,0)}</b></div><div className="match-stat"><span>HS</span><b>{P(m.hsPercent)}</b></div><div className="match-stat"><span>RATING</span><b>{N(m.rating,2)}</b></div></article>):<div className="empty-line">История матчей пока недоступна для этого источника.</div>}</div>}
function RankHistory({items}:{items:any[]}){return <div className="rank-history">{items?.length?items.map((x:any,i:number)=><div className="season" key={`${x.season}-${i}`}><div className="season-icon"><span>S{x.season}</span></div><div className="season-main"><b>Premier · Season {x.season}</b><small>{x.wins!=null?`${x.wins} побед`:''}</small></div><strong>{x.rating!=null?N(x.rating):'—'}</strong><small className="best">best {x.best!=null?N(x.best):'—'}</small></div>):<div className="empty-line">История Premier недоступна.</div>}</div>}

export default function PlayerDashboard({steamid64}:{steamid64:string}){
 const router=useRouter();const[q,setQ]=useState(steamid64),[r,setR]=useState<any>(null),[err,setErr]=useState(''),[loading,setLoading]=useState(true),[tab,setTab]=useState('overview'),[theme,setTheme]=useState<'dark'|'light'>('dark');
 useEffect(()=>{const t=(localStorage.getItem('radar-theme') as 'dark'|'light')||'dark';setTheme(t);document.documentElement.dataset.theme=t;},[]);
 useEffect(()=>{let alive=true;(async()=>{setLoading(true);setErr('');try{const res=await fetch('/api/lookup?q='+encodeURIComponent(steamid64),{cache:'no-store'});const data=await res.json();if(!res.ok)throw new Error(data.error||'Не удалось загрузить профиль');if(alive)setR(data);}catch(e){if(alive)setErr(e instanceof Error?e.message:'Ошибка загрузки');}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[steamid64]);
 const toggle=()=>{const t=theme==='dark'?'light':'dark';setTheme(t);document.documentElement.dataset.theme=t;localStorage.setItem('radar-theme',t)};
 const search=(e:any)=>{e.preventDefault();if(/^7656119\d{10}$/.test(q.trim()))router.push('/player/'+q.trim());else router.push('/?q='+encodeURIComponent(q.trim()));};
 if(loading)return <div className="loading-screen"><div className="loader"/><span>LOADING PLAYER DATA</span></div>;
 if(err)return <main className="error-page"><span>PLAYER / ERROR</span><h1>Не удалось загрузить профиль</h1><p>{err}</p><button onClick={()=>router.push('/')}>Вернуться к поиску</button></main>;
 const cs=r?.csstats,le=r?.leetify,fc=r?.faceit,st=cs?.stats||{},rows=(le?.matches?.length?le.matches:cs?.matches)||[];const prem=r?.premier?.rating??cs?.premier?.rating??le?.ranks?.premier??null;const [tl,tc]=tier(prem);const played=st.played??le?.totals?.matches??rows.length,wins=st.wins??le?.totals?.wins??rows.filter((x:any)=>x.result==='win').length,loss=st.losses??le?.totals?.losses??rows.filter((x:any)=>x.result==='loss').length;const best=useMemo(()=>rows.length?[...rows].sort((a:any,b:any)=>(b.rating||0)-(a.rating||0))[0]:null,[rows]);const rankItems=le?.ranks?.competitive?.length?le.ranks.competitive.map((x:any)=>({level:Number(x.rank_id??x.rank??x.skill_level??x.level),map:x.map_name??x.mapName??'Competitive'})).filter((x:any)=>x.level>=1&&x.level<=18):cs?.competitiveRanks||[];const premierHistory=cs?.premier?.history||[];
 const all={...st,...(le?.totals||{})};
 return <div className="site"><header className="topbar"><button className="brand" onClick={()=>router.push('/')}><span>R</span><b>RADAR<small>CS2 PLAYER DATA</small></b></button><form className="top-search" onSubmit={search}><input value={q} onChange={e=>setQ(e.target.value)} placeholder="SteamID64 / Steam URL"/><button>SEARCH</button></form><button className="theme" onClick={toggle}>{theme==='dark'?'LIGHT':'DARK'}</button></header>
 <main className="player-wrap"><div className="crumb"><button onClick={()=>router.push('/')}>Players</button><span>/</span><b>{steamid64}</b></div>
 <section className="identity"><img src={r.profile.avatarfull} alt=""/><div className="identity-main"><div className="identity-title"><h1>{r.profile.personaname}</h1>{r.profile.personastate===1&&<span className="online">ONLINE</span>}</div><p>{steamid64}</p><div className="identity-links"><a href={r.profile.profileurl} target="_blank">Steam ↗</a>{fc?.url&&<a href={fc.url} target="_blank">FACEIT ↗</a>}<a href={`https://csstats.gg/player/${steamid64}`} target="_blank">CSStats ↗</a></div></div><div className="identity-side"><span className="source-dot"/> DATA CONNECTED<div>{r.bans?.VACBanned?'VAC BAN':'CLEAN'}</div></div></section>
 <nav className="tabs">{[['overview','Overview'],['matches','Matches'],['performance','Performance'],['ranks','Ranks']].map(([k,v])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{v}</button>)}</nav>
 {tab==='overview'&&<div className="content-stack"><section className="hero-stats"><div className="premier"><span>PREMIER</span><div className="premier-line"><strong style={{color:tc}}>{prem==null?'—':N(prem)}</strong><em style={{color:tc}}>{tl}</em></div><small>Season {r.premier?.season??cs?.premier?.season??'—'} · {r.premier?.ratingChange!=null?`${r.premier.ratingChange>=0?'+':''}${N(r.premier.ratingChange)} change`:''}</small></div><div className="faceit-block"><div className="faceit-top"><span>FACEIT</span>{fc?.avatar&&<img src={fc.avatar} alt=""/>}</div><div className="faceit-name">{fc?.nickname||'Not connected'}</div><div className="faceit-grid"><Metric label="LEVEL" value={N(fc?.cs2?.skill_level)}/><Metric label="ELO" value={N(fc?.cs2?.faceit_elo)}/><Metric label="WIN RATE" value={P(fc?.stats?.winRate)}/><Metric label="K/D" value={N(fc?.stats?.avgKd,2)}/></div></div></section>
 <Section eyebrow="CAREER" title="Core statistics"><div className="metric-grid six"><Metric label="K/D" value={N(st.kd??le?.totals?.kd,2)} sub={`${N(st.kills??le?.totals?.kills)} kills · ${N(st.deaths??le?.totals?.deaths)} deaths`}/><Metric label="ADR" value={N(st.adr??le?.totals?.adr,1)}/><Metric label="HS %" value={P(st.hsPercent??le?.totals?.hsPercent)}/><Metric label="WIN RATE" value={P(st.winRate??(played?wins/played*100:0))}/><Metric label="RATING" value={N(st.hltvRating??le?.totals?.rating,2)}/><Metric label="MATCHES" value={N(played)}/></div></Section>
 <Section eyebrow="PREMIER HISTORY" title="Rating by season"><RankHistory items={premierHistory}/></Section>
 <div className="split"><Section eyebrow="COMPETITIVE" title="Real in-game ranks"><div className="rank-grid">{rankItems.length?rankItems.map((x:any,i:number)=><div className="rank-item" key={`${x.map}-${i}`}><RankBadge level={x.level} size={92}/><div><b>{x.map}</b><span>Current rank</span></div></div>):<div className="empty-line">Реальные соревновательные ранги не найдены. Для них источник должен вернуть rank_id.</div>}</div></Section><Section eyebrow="BEST MATCH" title="Top performance">{best?<div className="best-match"><span>{String(best.map||'—').replace(/^de_/,'')}</span><strong>{N(best.rating,2)}</strong><small>{N(best.kills)}/{N(best.deaths)}/{N(best.assists)} · {best.score||'—'} · {P(best.hsPercent)}</small></div>:<div className="empty-line">Нет данных.</div>}</Section></div>
 <Section eyebrow="LAST 30" title="Recent matches"><Matches rows={rows.slice(0,30)}/></Section></div>}
 {tab==='matches'&&<Section eyebrow="MATCH HISTORY" title="Последние 30 матчей"><Matches rows={rows.slice(0,30)}/></Section>}
 {tab==='ranks'&&<div className="content-stack"><Section eyebrow="COMPETITIVE RANKS" title="Текущие ранги"><div className="rank-grid large">{rankItems.length?rankItems.map((x:any,i:number)=><div className="rank-item" key={`${x.map}-${i}`}><RankBadge level={x.level} size={110}/><div><b>{x.map}</b><span>{['Silver I','Silver II','Silver III','Silver IV','Silver Elite','Silver Elite Master','Gold Nova I','Gold Nova II','Gold Nova III','Gold Nova Master','Master Guardian I','Master Guardian II','Master Guardian Elite','Distinguished Master Guardian','Legendary Eagle','Legendary Eagle Master','Supreme Master First Class','The Global Elite'][x.level-1]||'Unknown rank'}</span></div></div>):<div className="empty-line">Источник не вернул реальные rank_id.</div>}</div></Section><Section eyebrow="PREMIER" title="Season history"><RankHistory items={premierHistory}/></Section></div>}
 {tab==='performance'&&<div className="content-stack"><Section eyebrow="30 MATCH SAMPLE" title="Расширенная статистика"><div className="metric-grid six">{Object.entries(all).filter(([,v])=>typeof v==='number').map(([k,v]:any)=><Metric key={k} label={labels[k]||k.replaceAll('_',' ')} value={N(v,2)}/>)}</div></Section><div className="split"><Section eyebrow="LEETIFY" title="Skill ratings"><div className="rating-bars">{['aim','positioning','utility','clutch','opening','ct_leetify','t_leetify'].map(k=><div key={k}><div><span>{k.replaceAll('_',' ')}</span><b>{N(le?.ratings?.[k],1)}</b></div><i><em style={{width:Math.min(100,Math.max(0,Number(le?.ratings?.[k]||0)))+'%'}}/></i></div>)}</div></Section><Section eyebrow="MAPS" title="Map performance"><div className="map-list">{(le?.mapStats||[]).map((m:any)=><div key={m.map}><b>{m.map.replace(/^de_/,'')}</b><span>{m.matches} games</span><strong>{N(m.rating,2)}</strong><em>{P(m.winRate)}</em></div>)}</div></Section></div></div>}
 <footer>Steam · CSStats · FACEIT · Leetify · Data may depend on source availability.</footer></main></div>;
}
